const dataRank = [
  {
    imagePath: 'images/image1.jpg',
    name: 'Investidor 1',
    porcentageMonth: 5.0,
    porcentageWeek: 4.0,
    porcentageday: 3.0,
    risk: 'high',
    active: true,
    id: 100001,
  },
  {
    imagePath: 'images/image2.jpg',
    name: 'Investidor 2',
    porcentageMonth: 4.5,
    porcentageWeek: 4.5,
    porcentageday: 3.5,
    risk: 'medium',
    active: true,
    id: 100002,
  },
  {
    imagePath: 'images/image3.jpg',
    name: 'Investidor 3',
    porcentageMonth: 4.0,
    porcentageWeek: 5.0,
    porcentageday: 4.0,
    risk: 'high',
    active: true,
    id: 100003,
  },
  {
    imagePath: 'mages/image4.jpg',
    name: 'Investidor 4',
    porcentageMonth: 3.5,
    porcentageWeek: 3.0,
    porcentageday: 4.5,
    risk: 'low',
    active: true,
    id: 100004,
  },
  {
    imagePath: 'mages/image5.jpg',
    name: 'Investidor 5',
    porcentageMonth: 3.0,
    porcentageWeek: 3.5,
    porcentageday: 5.0,
    risk: 'high',
    active: true,
    id: 100005,
  },
];

export default dataRank;
